[package]
name = "duckdb-telemetry-server"
version.workspace = true
edition.workspace = true

[features]
ui = ["quent-query-engine-server/ui"]
swagger = ["quent-query-engine-server/swagger"]

[dependencies]
axum = "0.8"
clap = { version = "4", features = ["derive", "env"] }
duckdb-telemetry-analyzer = { path = "../analyzer" }
duckdb-telemetry-model = { path = "../model", features = ["collector"] }
quent-collector = { git = "https://github.com/rapidsai/quent.git", rev = "a872bf1a113c6509ccb4347fc98b067bd6c1829f" }
quent-io = { git = "https://github.com/rapidsai/quent.git", rev = "a872bf1a113c6509ccb4347fc98b067bd6c1829f" }
quent-query-engine-server = { git = "https://github.com/rapidsai/quent.git", rev = "a872bf1a113c6509ccb4347fc98b067bd6c1829f" }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
tracing = "0.1"
uuid = "1"
