[package]
name = "duckdb-telemetry-bridge"
version.workspace = true
edition.workspace = true

[lib]
name = "duckdb_telemetry_bridge"
crate-type = ["staticlib"]

[dependencies]
cxx.workspace = true
duckdb-telemetry-model = { path = "../model" }

[build-dependencies]
cxx-build.workspace = true
duckdb-telemetry-model = { path = "../model" }
quent-codegen = { git = "https://github.com/rapidsai/quent.git", rev = "a872bf1a113c6509ccb4347fc98b067bd6c1829f" }

